[[main]]
  name = "Головна"
  url = "/uk/"
  weight = 1

[[main]]
  name = "Про нас"
  url = "/uk/pro-nas/"
  weight = 2

[[main]]
  name = "Пожертви"
  url = "/uk/pozhertvy/"
  weight = 3

[[main]]
  name = "Контакти"
  url = "/uk/kontakty/"
  weight = 4
