baseURL = 'https://kemo.uz.ua/'
title = 'KJMC Uzhhorod'

defaultContentLanguage = 'uk'
defaultContentLanguageInSubdir = true

[languages]
  [languages.uk]
    contentDir = 'content/uk'
    languageName = 'Українська'
    languageCode = 'uk'
    weight = 1
    title = 'КЄМО Ужгород — Єврейська Месіанська Громада'
    [languages.uk.params]
      description = 'Конгрегація Євреїв Месіанського Юдаїзму м. Ужгород'
      locale = 'uk_UA'
    [[languages.uk.menus.main]]
      name = 'Головна'
      url = '/uk/'
      weight = 1
    [[languages.uk.menus.main]]
      name = 'Про нас'
      url = '/uk/pro-nas/'
      weight = 2
    [[languages.uk.menus.main]]
      name = 'Пожертви'
      url = '/uk/pozhertvy/'
      weight = 3
    [[languages.uk.menus.main]]
      name = 'Контакти'
      url = '/uk/kontakty/'
      weight = 4

  [languages.en]
    contentDir = 'content/en'
    languageName = 'English'
    languageCode = 'en'
    weight = 2
    title = 'KJMC Uzhhorod — Messianic Jewish Congregation'
    [languages.en.params]
      description = 'Jewish Congregation of Messianic Judaism in the City of Uzhhorod, Transcarpathia, Ukraine'
      locale = 'en_US'
    [[languages.en.menus.main]]
      name = 'Home'
      url = '/en/'
      weight = 1
    [[languages.en.menus.main]]
      name = 'About'
      url = '/en/about/'
      weight = 2
    [[languages.en.menus.main]]
      name = 'Donate'
      url = '/en/donate/'
      weight = 3
    [[languages.en.menus.main]]
      name = 'Contact'
      url = '/en/contact/'
      weight = 4

[params]
  author = 'KJMC Uzhhorod'
  donateURL = 'https://donorbox.org/support-kjmc-uzhgorod-messianic-congregation-in-wartime-ukraine'
  youtube = 'https://www.youtube.com/@kemoUzhgorod'
  facebook = 'https://www.facebook.com/kjmc.uzhhorod'
  instagram = 'https://www.instagram.com/kjmc.uzhgorod'
  email = 'office@kemo.uz.ua'
  address = 'вул. Швабська 51а, 2-й поверх, Ужгород'
  edrpou = '45313979'
  shabbat = 'Щосуботи о 13:00'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[sitemap]
  changeFreq = 'weekly'
  priority = 0.5

enableRobotsTXT = true
